const ServiceCodeEnum = {
  1: "Medical Encounter",
  2: "PEP",
  3: "PrEP",
  4: "ART",
  5: "ARTIHPAI",
  6: "ART Follow-Up",
  7: "Under Five",
  8: "TB Screening",
  9: "TB Follow-Up",
  10: "ART Stable On Care",
  11: "Pediatric IHPAI",
  12: "Pediatric Follow-Up",
  13: "Pediatric Stable On Care",
  14: "ART Pediatric",
  15: "VMMC",
  16: "Surgery",
  17: "Nursing Plan",
  18: "Vital",
  19: "Pre-Transfusion Vital",
  20: "Intra-Transfusion Vital",
  21: "ANC Service",
  22: "ANC Labour And Delivery",
  23: "ANC Labour And Delivery PMTCT",
  24: "Postnatal Adult",
  25: "Postnatal Pediatric",
  26: "ANC Follow-Up",
  27: "Postnatal PMTCT Adult",
  28: "Postnatal PMTCT Pediatric",
  29: "ANC Initial Already On ART",
  30: "ANC 1st Time On ART",
  31: "ANC Follow-up PMTCT",
  32: "ANC Labour And Delivery Summary",
  33: "Family Planning",
  34: "Referral",
  35: "ANC Delivery Discharge Mother",
  36: "ANC Delivery Discharge Baby",
  37: "Medical Encounter IPD",
  38: "HTS",
  39: "Covax",
  40: "Covid",
  41: "Birth Records",
  42: "Death Records",
  43: "Investigation",
  44: "Prescriptions",
  45: "Dispensations",
  97: "Service Queue",
  98: "Service Point",
  99: "Message Handle Death Records",
};

export const EnumServiceCode = ServiceCodeEnum;
export default ServiceCodeEnum;

/**
 * export const EnumServiceCode = {
  1: "Vitals",
  2: "HTS",
  3: "MedicalEncounterGeneral",
  4: "PEP",
  5: "PrEP",
  6: "IPD",
  7: "NursingCare",
  8: "UnderFive",
  9: "ServiceQueue",
  10: "Pharmacy",
  11: "TBService",
  12: "VMMCServices",
  13: "Investigations",
  14: "PainScalingTool",
  15: "Surgery",
  16: "Referrals",
  17: "Covaxes",
  18: "Covid",
  19: "BirthRecord",
  20: "DeathRecord",
  21: "Partographs",
  22: "ART",
  23: "ANC",
  24: "ANCLabourDelivery",
  25: "ANCLabourDeliveryPMTCT",
  26: "Postnatal",
  27: "LabourDeliverySummary",
  28: "ANCDeliveryDischarge",
  29: "FamilyPlanning",
};
 */
